import { env } from 'cloudflare:workers';
import { db } from '@/lib/db';
import { hash, session, sameOrigin } from '@/lib/auth';
import { seed, type User } from '@/lib/bar';
export async function GET(req:Request){try{const u=await session(req),rows=await db().prepare('SELECT id,name,role FROM bar_users ORDER BY name').all<User>();return Response.json({user:u,staff:rows.results,setup:rows.results.length===0},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:'Не удалось загрузить данные. Попробуйте ещё раз.'},{status:503})}}
export async function POST(req:Request){try{sameOrigin(req);const a=await req.json() as Record<string,unknown>;const binding=db();if(a.type==='logout'){const token=req.headers.get('cookie')?.match(/bar_session=([^;]+)/)?.[1];if(token)await binding.prepare('DELETE FROM bar_sessions WHERE token=?').bind(token).run();return Response.json({ok:true},{headers:{'Set-Cookie':'bar_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'}})}
 if(a.type==='setup'||a.type==='staff'){const count=await binding.prepare('SELECT COUNT(*) n FROM bar_users').first<{n:number}>();if(a.type==='setup'){const key=(env as unknown as {SETUP_KEY?:string}).SETUP_KEY;if(!key||a.setupKey!==key)throw Error('Введите код первого запуска владельца');}if(a.type==='setup'&&count!.n>0)throw Error('Администратор уже создан');const actor=await session(req);if(a.type==='staff'&&actor?.role!=='admin')throw Error('Нужен администратор');if(typeof a.name!=='string'||!a.name.trim()||a.name.length>60)throw Error('Введите имя');if(typeof a.pin!=='string'||!/^\d{6,12}$/.test(a.pin))throw Error('PIN должен содержать от 6 до 12 цифр');const role=a.type==='setup'?'admin':a.role==='bar'||a.role==='kitchen'?'cook':a.role;if(typeof role!=='string'||!['admin','waiter','cook'].includes(role))throw Error('Неверная роль');const salt=crypto.randomUUID(),id=a.type==='setup'?'owner':crypto.randomUUID();const insertUser=binding.prepare('INSERT INTO bar_users (id,name,role,hash,salt) VALUES (?,?,?,?,?)').bind(id,a.name.trim(),role,await hash(a.pin,salt),salt);if(a.type==='setup')await binding.batch([insertUser,binding.prepare('INSERT INTO bar_state (id,revision,data) VALUES (1,0,?)').bind(JSON.stringify(seed()))]);else await insertUser.run();return Response.json({ok:true});}
 if(a.type!=='login')throw Error('Неверное действие');const attempt=await binding.prepare('SELECT count,until FROM bar_attempts WHERE id=?').bind(String(a.id)).first<{count:number;until:number}>();if(attempt&&attempt.count>=5&&attempt.until>Date.now())return Response.json({error:'Слишком много попыток. Повторите через 15 минут.'},{status:429});const u=await binding.prepare('SELECT * FROM bar_users WHERE id=?').bind(String(a.id)).first<User&{hash:string;salt:string}>();if(!u||typeof a.pin!=='string'||a.pin.length>12||await hash(a.pin,u.salt)!==u.hash){await binding.prepare('INSERT INTO bar_attempts (id,count,until) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=?').bind(String(a.id),Date.now()+900000,Date.now(),Date.now()+900000).run();throw Error('Неверный PIN');}const token=crypto.randomUUID()+crypto.randomUUID();await binding.batch([binding.prepare('DELETE FROM bar_attempts WHERE id=?').bind(u.id),binding.prepare('DELETE FROM bar_sessions WHERE expires<?').bind(Date.now()),binding.prepare('INSERT INTO bar_sessions (token,user_id,expires) VALUES (?,?,?)').bind(token,u.id,Date.now()+12*3600000)]);return Response.json({ok:true},{headers:{'Set-Cookie':`bar_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=43200${new URL(req.url).protocol==='https:'?'; Secure':''}`}});
 }catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'Ошибка сохранения'},{status:400})}}
