'use client';
import { useState } from 'react';
import type { State, Action } from '@/lib/bar';
import { inventoryRows, stockSignature, rounded, stamp, type InventoryRow } from '@/lib/inventory';

function Report({rows}:{rows:InventoryRow[]}){
 return <div className="table-wrap"><table><thead><tr><th>Наименование</th><th>Ед.</th><th>На начало</th><th>Приход</th><th>Расход</th><th>Ожидалось</th><th>Факт</th><th>Расхождение</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.unit}</td><td>{r.opening}</td><td>{r.received}</td><td>{r.consumed}</td><td>{r.expected}</td><td><b>{r.actual}</b></td><td className={r.difference<0?'red-text':''}>{r.difference>0?'+':''}{r.difference} {r.difference<0?'· недостача':r.difference>0?'· излишек':''}</td></tr>)}</tbody></table></div>;
}
export default function InventoryPanel({state,busy,action}:{state:State;busy:boolean;action:(a:Action)=>Promise<boolean>}){
 const [draft,setDraft]=useState<State|null>(null),[counts,setCounts]=useState<Record<string,string>>({});
 const stale=!!draft&&stockSignature(draft)!==stockSignature(state);
 const records=state.inventories??[];
 const base=state.stockBaseline;
 const rows=inventoryRows(draft??state);
 return <div className="inventory-workspace">
 <section className="panel">
  <div className="panel-title"><h2>{draft?'Новая инвентаризация':'Текущий период'}</h2>{!draft&&<button className="primary" disabled={busy} onClick={()=>{setCounts({});setDraft(structuredClone(state))}}>Ввести фактические остатки</button>}</div>
  <div className="panel-footer">Начало периода: {base?stamp((draft??state).inventories?.at(-1)?.at??base.at):'—'} · время московское.<br/>Ожидаемый остаток = на начало + приход − расход по техкартам. Расхождение = факт − ожидаемый остаток.</div>
  {draft?<form onSubmit={async e=>{e.preventDefault();if(await action({type:'inventory',counts,signature:stockSignature(draft)}))setDraft(null)}}>
   {stale&&<div className="warning-box" role="alert">Во время пересчёта изменился склад. <button type="button" className="secondary" onClick={()=>setDraft(structuredClone(state))}>Обновить расчёт</button> После обновления перепроверьте введённые значения.</div>}
   <div className="table-wrap"><table><thead><tr><th>Наименование</th><th>На начало</th><th>Приход</th><th>Расход</th><th>Ожидалось</th><th>Фактический остаток</th><th>Расхождение</th></tr></thead><tbody>{rows.map(r=>{const value=counts[r.id]??'',delta=value===''?null:rounded(Number(value)-r.expected);return <tr key={r.id}><td>{r.name}<small className="muted"> · {r.unit}</small></td><td>{r.opening}</td><td>{r.received}</td><td>{r.consumed}</td><td>{r.expected}</td><td><input aria-label={`Фактический остаток: ${r.name}, ${r.unit}`} style={{minWidth:110,maxWidth:170}} type="number" inputMode="decimal" min="0" max="1000000000" step="0.001" required value={value} onChange={e=>setCounts(c=>({...c,[r.id]:e.target.value}))} placeholder={r.unit}/></td><td className={delta!==null&&delta<0?'red-text':''}>{delta===null?'—':`${delta>0?'+':''}${delta}`}</td></tr>})}</tbody></table></div>
   <div className="panel-footer"><p>Заполните все позиции, включая нулевые. При сохранении фиксируются время и сотрудник. Фактические остатки станут началом следующего периода.</p><div className="heading-actions"><button className="primary" disabled={busy||stale}>Зафиксировать инвентаризацию</button><button type="button" className="secondary" disabled={busy} onClick={()=>setDraft(null)}>Отмена</button></div></div>
  </form>:<div className="table-wrap"><table><thead><tr><th>Наименование</th><th>Ед.</th><th>На начало</th><th>Приход</th><th>Расход по техкартам</th><th>Ожидалось сейчас</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.unit}</td><td>{r.opening}</td><td>{r.received}</td><td>{r.consumed}</td><td><b>{r.expected}</b></td></tr>)}</tbody></table></div>}
 </section>
 <section className="panel"><div className="panel-title"><h2>История инвентаризаций</h2><span>{records.length} проверок</span></div>{records.length?records.slice().reverse().map(inv=><details className="shift-report" key={inv.id}><summary>{stamp(inv.at)} · {inv.who} · расхождений: {inv.rows.filter(r=>r.difference!==0).length}</summary><div className="panel-footer">Период: {stamp(inv.from)} — {stamp(inv.at)} · Москва</div><Report rows={inv.rows}/></details>):<div className="simple-empty">Проверок пока нет. Введите фактические остатки и сохраните первую инвентаризацию.</div>}</section>
 {base&&<section className="panel"><div className="panel-title"><h2>Начальные показания</h2></div><details className="shift-report"><summary>Начало учёта остатков · {stamp(base.at)}</summary><div className="panel-footer">Остатки, сохранённые при включении инвентаризации. Движения до этой даты не восстанавливаются задним числом.</div><div className="table-wrap"><table><thead><tr><th>Наименование</th><th>Начальный остаток</th></tr></thead><tbody>{base.items.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.qty} {i.unit}</td></tr>)}</tbody></table></div></details>{state.shifts.slice().reverse().map(sh=><details className="shift-report" key={sh.id}><summary>Начало работы · {stamp(sh.opened)} · смена {sh.date}</summary>{sh.openingStock?<div className="table-wrap"><table><thead><tr><th>Наименование</th><th>Остаток при открытии</th></tr></thead><tbody>{sh.openingStock.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.qty} {i.unit}</td></tr>)}</tbody></table></div>:<div className="panel-footer">Для этой смены начальные остатки ещё не фиксировались.</div>}</details>)}</section>}
 {state.shifts.some(sh=>sh.closed&&sh.stockCounts)&&<section className="panel"><div className="panel-title"><h2>Архив пересчётов при закрытии смен</h2></div>{state.shifts.filter(sh=>sh.closed&&sh.stockCounts).slice().reverse().map(sh=><details className="shift-report" key={sh.id}><summary>{stamp(sh.closed!)} · смена {sh.date}</summary><div className="table-wrap"><table><thead><tr><th>Наименование</th><th>Ожидалось</th><th>Факт</th><th>Расхождение</th></tr></thead><tbody>{Object.entries(sh.stockCounts!).map(([id,qty])=>{const i=state.ingredients.find(i=>i.id===id),expected=sh.stockExpected?.[id];return <tr key={id}><td>{i?.name??id}</td><td>{expected??'—'} {i?.unit}</td><td>{qty} {i?.unit}</td><td>{expected===undefined?'—':rounded(qty-expected)}</td></tr>})}</tbody></table></div></details>)}</section>}
 </div>;
}
