'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {LayoutDashboard,Utensils,ChefHat,Package,Check,BookOpen,History,Users,LogOut,Plus,RefreshCw,AlertTriangle,Banknote,CreditCard} from 'lucide-react';
import InventoryPanel from './inventory-panel';
import {type Action,type Order,type Product,type State,type User,current,expectedCash,money,roleNames,shiftOrders,total} from '@/lib/bar';

type Auth={user:User|null;staff:User[];setup:boolean};
const clock=(v:string)=>new Date(v).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'});
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="field"><span>{title}</span>{children}</label>}
export default function Home(){
 const [auth,setAuth]=useState<Auth|null>(null),[state,setState]=useState<State|null>(null),[revision,setRevision]=useState(0),[view,setView]=useState('overview'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [table,setTable]=useState('Стол 1'),[cart,setCart]=useState<Record<string,number>>({}),[selected,setSelected]=useState<Order|null>(null);
 const accept=useCallback((d:{state:State;revision:number})=>{setState(d.state);setRevision(d.revision)},[]);
 async function json(r:Response){const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка');return d}
 async function loadAuth(){setAuth(await json(await fetch('/api/auth',{cache:'no-store'})))}
 async function load(){if(!auth?.user)return;accept(await json(await fetch('/api/state',{cache:'no-store'})))}
 useEffect(()=>{loadAuth().catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!auth?.user)return;load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),5000);return()=>clearInterval(t)},[auth?.user?.id]);
 async function act(action:Action){setBusy(true);setError('');try{const d=await json(await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,action})}));accept(d);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function authAct(payload:Record<string,unknown>){setBusy(true);setError('');try{await json(await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));setState(null);await loadAuth()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function form(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget).entries())}
 if(!auth)return <main className="center"><RefreshCw/>Загрузка…</main>;
 if(!auth.user)return <main className="login"><div className="logo">M</div><h1>MALINA · Бар</h1><p>{auth.setup?'Первый запуск: создайте администратора':'Выберите сотрудника и введите PIN'}</p>{error&&<div className="alert"><AlertTriangle size={18}/>{error}</div>}<form onSubmit={e=>{const f=form(e);authAct({...f,type:auth.setup?'setup':'login'})}}>{auth.setup?<><Field title="Имя"><input name="name" required/></Field><Field title="Код первого запуска"><input name="setupKey" type="password" required/></Field></>:<Field title="Сотрудник"><select name="id">{auth.staff.map(u=><option value={u.id} key={u.id}>{u.name} · {roleNames[u.role]}</option>)}</select></Field>}<Field title="PIN"><input name="pin" type="password" inputMode="numeric" pattern="[0-9]{6,12}" required/></Field><button className="primary wide" disabled={busy}>{busy?'Сохраняем…':auth.setup?'Создать администратора':'Войти'}</button></form></main>;
 if(!state)return <main className="center">Загрузка смены…</main>;
 const user=auth.user,admin=user.role==='admin',shift=current(state),orders=shiftOrders(state,shift?.id),openOrders=orders.filter(o=>!o.paid&&total(o)>0);
 const nav=[
  ['overview','Обзор',LayoutDashboard,['admin']],['orders','Заказы',Utensils,['admin','waiter']],['preparation','Приготовление',ChefHat,['admin','cook','bar','kitchen']],
  ['stock','Склад',Package,['admin']],['inventory','Инвентаризация',Check,['admin']],['menu','Меню',BookOpen,['admin']],['logs','Журнал',History,['admin']],['staff','Сотрудники',Users,['admin']]
 ].filter(([, , ,roles])=>(roles as string[]).includes(user.role));
 const actual=nav.some(n=>n[0]===view)?view:String(nav[0]?.[0]??'orders');
 const active=selected?state.orders.find(o=>o.id===selected.id):null;
 return <div className="app">
  <aside><div className="brand"><div className="mark">M</div><div>MALINA<small>БАР · УЧЁТ</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={String(id)} className={actual===id?'active':''} onClick={()=>setView(String(id))}><Icon size={18}/>{String(label)}</button>)}</nav><button className="profile" onClick={()=>authAct({type:'logout'})}><span>{user.name}<small>{roleNames[user.role]}</small></span><LogOut size={18}/></button></aside>
  <main className="workspace"><header><b>{nav.find(n=>n[0]===actual)?.[1]}</b><span className={shift?'status on':'status'}>{shift?'Смена открыта':'Смена закрыта'}</span></header>
  {error&&<div className="alert"><AlertTriangle size={18}/>{error}<button onClick={()=>setError('')}>×</button></div>}
  <div className="content">
  {actual==='overview'&&admin&&<><div className="heading"><div><h1>Обзор смены</h1><p>Касса, заказы и текущая работа бара.</p></div>{shift?<button className="danger" disabled={busy} onClick={async()=>{const cash=prompt('Фактические наличные, ₽',String(expectedCash(state,shift)));if(cash!==null)await act({type:'close',cash})}}>Закрыть смену</button>:<button className="primary" disabled={busy} onClick={async()=>{const cash=prompt('Размен в кассе, ₽','0');if(cash!==null)await act({type:'open',cash})}}>Открыть смену</button>}</div><div className="cards"><div className="card"><span>Открытые заказы</span><strong>{openOrders.length}</strong></div><div className="card"><span>Выручка</span><strong>{money(orders.filter(o=>o.paid).reduce((n,o)=>n+total(o),0))}</strong></div><div className="card"><span>Наличные ожидаемо</span><strong>{shift?money(expectedCash(state,shift)):'—'}</strong></div></div></>}
  {actual==='orders'&&<><div className="heading"><div><h1>Заказы и столы</h1><p>{shift?'Работа идёт в текущей смене':'Сначала администратор должен открыть смену'}</p></div><button className="primary" disabled={!shift||busy} onClick={()=>{setCart({});setTable('Стол 1');setSelected({id:'new'} as Order)}}><Plus size={17}/>Новый заказ</button></div><div className="grid">{orders.slice().reverse().map(o=><button className="order" key={o.id} onClick={()=>setSelected(o)}><div><b>{o.table}</b><small>{o.employee} · {clock(o.created)}</small></div><strong>{money(total(o))}</strong><span>{o.paid?'Оплачен':'Открыт'}</span></button>)}{!orders.length&&<div className="empty">Заказов в смене пока нет.</div>}</div></>}
  {actual==='preparation'&&<><div className="heading"><div><h1>Приготовление</h1><p>Бар и кухня объединены в одно рабочее место.</p></div></div><div className="grid">{orders.flatMap(o=>o.lines.map(l=>({o,l}))).filter(x=>x.l.status==='ordered'||x.l.status==='ready').map(({o,l})=><div className="ticket" key={l.id}><b>{l.qty} × {l.name}</b><small>{o.table} · {o.employee}</small><div className="row">{l.status==='ordered'?<button className="primary" disabled={busy} onClick={()=>act({type:'status',orderId:o.id,lineId:l.id,status:'ready'})}>Готово</button>:<button className="primary" disabled={busy} onClick={()=>act({type:'status',orderId:o.id,lineId:l.id,status:'served'})}>Выдано</button>}</div></div>)}</div></>}
  {actual==='stock'&&admin&&<><div className="heading"><div><h1>Склад</h1><p>Фактические остатки и приход.</p></div><button className="primary" onClick={async()=>{const name=prompt('Название ингредиента');if(!name)return;const unit=prompt('Единица: мл / г / шт / порц','шт');if(unit)await act({type:'ingredient',name,unit})}}>Добавить позицию</button></div><div className="table">{state.ingredients.map(i=><div className="tr" key={i.id}><span>{i.name}<small>{i.kind==='prepared'?'Заготовка':''}</small></span><b>{i.qty} {i.unit}</b><button onClick={async()=>{const qty=prompt(`Приход ${i.name}, ${i.unit}`);if(!qty)return;const reason=prompt('Основание','Приход')||'Приход';await act({type:'stock',id:i.id,qty,reason})}}>+ Приход</button></div>)}</div></>}
  {actual==='inventory'&&admin&&<InventoryPanel state={state} busy={busy} action={act}/>}
  {actual==='menu'&&admin&&<><div className="heading"><div><h1>Меню и техкарты</h1><p>Позиции без техкарты нельзя добавить в заказ.</p></div></div><div className="table">{state.menu.map(p=><div className="tr" key={p.id}><span>{p.name}<small>{p.station==='bar'?'Напитки':'Блюда'} · {p.recipe.length?'техкарта заполнена':'нужна техкарта'}</small></span><b>{money(p.price)}</b><button onClick={()=>act({type:'toggleProduct',id:p.id})}>{p.active?'Скрыть':'Включить'}</button></div>)}</div></>}
  {actual==='logs'&&admin&&<div className="panel"><h2>Журнал действий</h2>{state.logs.slice(0,100).map(l=><div className="log" key={l.id}><span>{clock(l.at)}</span><div>{l.text}<small>{l.who}</small></div></div>)}</div>}
  {actual==='staff'&&admin&&<><div className="heading"><div><h1>Сотрудники</h1></div><button className="primary" onClick={async()=>{const name=prompt('Имя сотрудника');if(!name)return;const pin=prompt('PIN 6–12 цифр');if(!pin)return;const role=prompt('Роль: waiter или cook','waiter');if(role)await authAct({type:'staff',name,pin,role})}}>Добавить</button></div><div className="table">{auth.staff.map(u=><div className="tr" key={u.id}><span>{u.name}</span><b>{roleNames[u.role]}</b></div>)}</div></>}
  </div></main>
  {active&&active.id!=='new'&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="modal"><button className="close" onClick={()=>setSelected(null)}>×</button><h2>{active.table}</h2><p>{active.employee} · {clock(active.created)}</p>{active.lines.map(l=><div className="line" key={l.id}><span>{l.qty} × {l.name}<small>{l.status}</small></span><b>{money(l.price*l.qty)}</b>{!active.paid&&l.status==='ready'&&<button onClick={()=>act({type:'status',orderId:active.id,lineId:l.id,status:'served'})}>Выдано</button>}</div>)}<div className="total">Итого <b>{money(total(active))}</b></div>{!active.paid&&<div className="pay"><button className="primary" onClick={()=>act({type:'pay',orderId:active.id,method:'cash'})}><Banknote size={17}/>Наличные</button><button onClick={()=>act({type:'pay',orderId:active.id,method:'card'})}><CreditCard size={17}/>Карта</button></div>}</div></div>}
  {selected?.id==='new'&&<div className="overlay"><div className="modal large"><button className="close" onClick={()=>setSelected(null)}>×</button><h2>Новый заказ</h2><Field title="Стол / гость"><input value={table} onChange={e=>setTable(e.target.value)}/></Field><div className="products">{state.menu.filter(p=>p.active).map((p:Product)=><button key={p.id} disabled={!p.recipe.length} onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}))}><span>{p.name}<small>{p.recipe.length?'':'Нужна техкарта'}</small></span><b>{money(p.price)}</b></button>)}</div><div className="basket">{Object.entries(cart).filter(([,q])=>q>0).map(([id,q])=>{const p=state.menu.find(p=>p.id===id)!;return <div className="basketline" key={id}><span>{q} × {p.name}</span><b>{money(p.price*q)}</b><button onClick={()=>setCart(c=>({...c,[id]:Math.max(0,q-1)}))}>−</button></div>})}</div><button className="primary wide" disabled={!Object.values(cart).some(Boolean)||busy} onClick={async()=>{if(await act({type:'order',table,cart:Object.entries(cart).filter(([,q])=>q>0).map(([id,qty])=>({id,qty}))}))setSelected(null)}}>Создать заказ</button></div></div>}
 </div>
}