import { installInventory, inventoryRows, stockSignature, rounded, type StockSnapshot, type StockMovement, type InventoryRecord } from './inventory';
export type Role='admin'|'waiter'|'cook'|'bar'|'kitchen';
export type User={id:string;name:string;role:Role};
export type Ingredient={id:string;name:string;unit:string;qty:number;kind?:'prepared'};
export type Product={id:string;name:string;price:number;station:'bar'|'kitchen';recipe:{id:string;qty:number}[];active:boolean;recipeNote?:string};
export type Line={id:string;name:string;price:number;qty:number;station:'bar'|'kitchen';recipe:{id:string;qty:number}[];status:'ordered'|'ready'|'served'|'cancelled';reason?:string};
export type Order={id:string;table:string;employee:string;shiftId:string;created:string;lines:Line[];paid?:'cash'|'card';paidAt?:string};
export type Shift={id:string;date:string;opened:string;openingCash:number;openingStock?:Ingredient[];closed?:string;actualCash?:number;stockCounts?:Record<string,number>;stockExpected?:Record<string,number>;expectedCash?:number};
export type State={ingredients:Ingredient[];menu:Product[];orders:Order[];shifts:Shift[];logs:{id:string;at:string;who:string;text:string;shiftId?:string}[];cashExpenses:{id:string;shiftId:string;amount:number;reason:string}[];stockBaseline?:StockSnapshot;stockMovements?:StockMovement[];inventories?:InventoryRecord[];catalogUpdates?:string[]};
export const roleNames:Record<Role,string>={admin:'Администратор',waiter:'Официант',cook:'Повар-бармен',bar:'Повар-бармен',kitchen:'Повар-бармен'};
export const isPreparationStaff=(role:Role)=>role==='cook'||role==='bar'||role==='kitchen';
export const money=(v:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(v);
export const total=(o:Order)=>o.lines.filter(l=>l.status!=='cancelled').reduce((n,l)=>n+l.price*l.qty,0);
export const current=(s:State)=>s.shifts.find(x=>!x.closed);
export const shiftOrders=(s:State,id?:string)=>s.orders.filter(o=>o.shiftId===id);
export const expectedCash=(s:State,sh:Shift)=>sh.openingCash+shiftOrders(s,sh.id).filter(o=>o.paid==='cash').reduce((n,o)=>n+total(o),0)-s.cashExpenses.filter(e=>e.shiftId===sh.id).reduce((n,e)=>n+e.amount,0);
export const seed=():State=>({ingredients:[{id:'rum',name:'Белый ром',unit:'мл',qty:0},{id:'cola',name:'Кола',unit:'мл',qty:0},{id:'puree',name:'Пюре малины',unit:'мл',qty:0},{id:'lemon',name:'Лимонный сок',unit:'мл',qty:0},{id:'burger',name:'Бургер, заготовка',unit:'шт',qty:0},{id:'fries',name:'Картофель фри',unit:'г',qty:0}],menu:[{id:'rc',name:'Ром-кола',price:450,station:'bar',active:true,recipe:[{id:'rum',qty:50},{id:'cola',qty:150}]},{id:'mr',name:'Malina Rum',price:550,station:'bar',active:true,recipe:[{id:'rum',qty:50},{id:'puree',qty:30},{id:'lemon',qty:20}]},{id:'c',name:'Кола',price:200,station:'bar',active:true,recipe:[{id:'cola',qty:250}]},{id:'b',name:'Бургер',price:650,station:'kitchen',active:true,recipe:[{id:'burger',qty:1}]},{id:'f',name:'Картофель фри',price:250,station:'kitchen',active:true,recipe:[{id:'fries',qty:150}]}],orders:[],shifts:[],logs:[],cashExpenses:[]});
export type Action={type:string;[key:string]:unknown};
function num(v:unknown,min=0){const n=Number(v);if(!Number.isFinite(n)||n<min||n>1e9)throw Error('Введите корректное число');return n;}
function str(v:unknown){if(typeof v!=='string'||!v.trim()||v.length>300)throw Error('Заполните обязательные поля');return v.trim();}
export function apply(state:State,a:Action,user:User):State{
 const s=structuredClone(installInventory(state)),now=new Date().toISOString(),id=()=>crypto.randomUUID(),admin=()=>{if(user.role!=='admin')throw Error('Нужен администратор')};let sh=current(s),description='';
 const needShift=()=>{if(!sh)throw Error('Сначала откройте смену');return sh};
 const order=()=>{const o=s.orders.find(x=>x.id===a.orderId);if(!o||o.shiftId!==needShift().id)throw Error('Заказ недоступен');return o};
 switch(a.type){
 case 'open':admin();if(sh)throw Error('Смена уже открыта');sh={id:id(),date:new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow'}).format(new Date()),opened:now,openingCash:num(a.cash),openingStock:structuredClone(s.ingredients)};s.shifts.push(sh);description=`Открыта смена • размен ${money(sh.openingCash)}`;break;
 case 'order':{if(!['admin','waiter'].includes(user.role))throw Error('Заказы создаёт официант');needShift();const table=str(a.table);const cart=a.cart as {id:string;qty:number}[];if(!Array.isArray(cart)||!cart.length||cart.length>100)throw Error('Добавьте позиции');const lines=cart.map(c=>{const p=s.menu.find(p=>p.id===c.id&&p.active);if(!p)throw Error('Позиция меню недоступна');if(!p.recipe.length)throw Error(`Для «${p.name}» заполните техкарту перед продажей`);const qty=num(c.qty,1);if(!Number.isInteger(qty)||qty>99)throw Error('Количество от 1 до 99');return {...structuredClone(p),id:id(),qty,status:'ordered' as const}});const o:Order={id:id(),table,employee:user.name,shiftId:sh!.id,created:now,lines};s.orders.push(o);description=`Заказ ${o.id.slice(0,6)} • ${table} • ${money(total(o))}`;break;}
 case 'status':{const o=order();if(o.paid)throw Error('Заказ уже оплачен');const l=o.lines.find(l=>l.id===a.lineId);if(!l)throw Error('Позиция не найдена');if(a.status==='ready'){if(!isPreparationStaff(user.role)&&user.role!=='admin')throw Error('Приготовление подтверждает повар-бармен');if(l.status!=='ordered')throw Error('Позиция уже обработана');for(const r of l.recipe){const i=s.ingredients.find(i=>i.id===r.id);if(!i||i.qty+1e-6<r.qty*l.qty)throw Error(`Недостаточно: ${i?.name??r.id}. Оформите приход на склад`)}for(const r of l.recipe){const i=s.ingredients.find(i=>i.id===r.id)!;const used=rounded(r.qty*l.qty);i.qty=rounded(i.qty-used);s.stockMovements!.push({id:id(),at:now,who:user.name,ingredientId:i.id,kind:'consumption',qty:used,shiftId:sh!.id,orderId:o.id,lineId:l.id});}l.status='ready';description=`Приготовлено: ${l.name} × ${l.qty} • ${o.table}`;}else if(a.status==='served'){if(!['admin','waiter'].includes(user.role)&&!isPreparationStaff(user.role))throw Error('Нет доступа к выдаче');if(l.status!=='ready')throw Error('Сначала подтвердите приготовление');l.status='served';description=`Выдано: ${l.name} × ${l.qty} • ${o.table}`;}else throw Error('Неверный статус');break;}
 case 'cancel':{const o=order();if(o.paid)throw Error('Оплаченный заказ нельзя отменить');const l=o.lines.find(l=>l.id===a.lineId);if(!l||l.status==='cancelled')throw Error('Позиция уже отменена');if(user.role!=='waiter')admin();if(l.status!=='ordered')admin();l.reason=str(a.reason);const before=l.status;l.status='cancelled';description=`Отмена ${before==='ordered'?'до':'после'} приготовления: ${l.name} × ${l.qty} • ${o.table} • ${l.reason}. ${before==='ordered'?'Без списания':'Ингредиенты остаются списанными'}`;break;}
 case 'pay':{if(!['admin','waiter'].includes(user.role))throw Error('Оплату принимает официант');const o=order();if(o.paid)throw Error('Оплата уже записана');const live=o.lines.filter(l=>l.status!=='cancelled');if(!live.length||live.some(l=>l.status!=='served'))throw Error('Выдайте все позиции перед оплатой');if(a.method!=='cash'&&a.method!=='card')throw Error('Выберите тип оплаты');o.paid=a.method;o.paidAt=now;description=`Оплата ${o.table} • ${money(total(o))} • ${a.method==='cash'?'наличные':'карта'}`;break;}
 case 'stock':{admin();const i=s.ingredients.find(i=>i.id===a.id);if(!i)throw Error('Ингредиент не найден');const qty=num(a.qty,0.001);i.qty=rounded(i.qty+qty);s.stockMovements!.push({id:id(),at:now,who:user.name,ingredientId:i.id,kind:'receipt',qty:rounded(qty),shiftId:sh?.id});description=`Приход: ${i.name} +${qty} ${i.unit} • ${str(a.reason)}`;break;}
 case 'ingredient':{admin();const i={id:id(),name:str(a.name),unit:str(a.unit),qty:0};s.ingredients.push(i);description=`Новый ингредиент: ${i.name}`;break;}
 case 'product':{admin();const recipe=a.recipe as {id:string;qty:number}[];if(!Array.isArray(recipe)||!recipe.length||new Set(recipe.map(r=>r.id)).size!==recipe.length)throw Error('Заполните техкарту без повторов');for(const r of recipe){if(!s.ingredients.some(i=>i.id===r.id))throw Error('Ингредиент не найден');r.qty=num(r.qty,0.001)}if(a.station!=='bar'&&a.station!=='kitchen')throw Error('Выберите станцию');const p:Product={id:typeof a.id==='string'?a.id:id(),name:str(a.name),price:num(a.price,1),station:a.station,recipe,active:true};const idx=s.menu.findIndex(x=>x.id===p.id);if(idx>=0)s.menu[idx]=p;else s.menu.push(p);description=`Сохранено меню: ${p.name} • ${money(p.price)}`;break;}
 case 'toggleProduct':admin();{const p=s.menu.find(x=>x.id===a.id);if(!p)throw Error('Позиция не найдена');p.active=!p.active;description=`${p.active?'Включено':'Скрыто'} в меню: ${p.name}`;}break;
 case 'expense':admin();needShift();{const e={id:id(),shiftId:sh!.id,amount:num(a.amount,0.01),reason:str(a.reason)};s.cashExpenses.push(e);description=`Расход из кассы ${money(e.amount)} • ${e.reason}`;}break;
 case 'inventory':{admin();if(a.signature!==stockSignature(s))throw Error('Остатки изменились во время пересчёта. Обновите расчёт и проверьте фактические значения.');const counts=a.counts as Record<string,unknown>;if(!counts||typeof counts!=='object'||Array.isArray(counts))throw Error('Введите фактические остатки');const rows=inventoryRows(s);for(const r of rows){const v=counts[r.id];if((typeof v!=='string'&&typeof v!=='number')||String(v).trim()==='')throw Error(`Пересчитайте: ${r.name}`);r.actual=rounded(num(v));r.difference=rounded(r.actual-r.expected);const i=s.ingredients.find(i=>i.id===r.id)!;if(Math.abs(i.qty-r.expected)>0.001)throw Error('Расчёт остатков не совпадает со складом. Проверка не сохранена.');i.qty=r.actual;}s.inventories!.push({id:id(),at:now,who:user.name,from:s.inventories!.at(-1)?.at??s.stockBaseline!.at,movementEnd:s.stockMovements!.length,rows,shiftId:sh?.id});description=`Инвентаризация • позиций: ${rows.length} • с расхождением: ${rows.filter(r=>r.difference!==0).length}`;break;}
 case 'close':{admin();needShift();const open=shiftOrders(s,sh!.id).filter(o=>!o.paid&&total(o)>0);if(open.length)throw Error(`Не закрыто заказов: ${open.length}. Оплатите или оформите отмены`);sh!.actualCash=num(a.cash);sh!.expectedCash=expectedCash(s,sh!);sh!.closed=now;description=`Смена закрыта • касса: ${money(sh!.actualCash-sh!.expectedCash)} расхождение`;break;}
 default:throw Error('Неизвестное действие');
 }
 s.logs.unshift({id:id(),at:now,who:user.name,text:description,shiftId:sh?.id});return s;
}
