import fs from 'node:fs';
const p='worker-direct.js';
let s=fs.readFileSync(p,'utf8');
const scriptStart=s.indexOf('<script>(()=>{const f=document.querySelector');
if(scriptStart<0)throw Error('autosave script start missing');
const scriptEnd=s.indexOf('</script>',scriptStart);
if(scriptEnd<0)throw Error('autosave script end missing');
s=s.slice(0,scriptStart)+s.slice(scriptEnd+9);
const old=`<div class=\"card\"><div class=\"muted\" id=\"autosaveState\">Изменения сохраняются автоматически</div></div>`;
const neu=`<div class=\"card\"><button class=\"btn primary full\" type=\"submit\">Сохранить изменения</button><div class=\"muted\" style=\"margin-top:8px\">После изменения данных нажмите «Сохранить изменения»</div></div>`;
if(!s.includes(old))throw Error('current autosave status block missing');
s=s.replace(old,neu);
if(s.includes('id=\"autosaveState\"')||s.includes('<script>(()=>{const f=document.querySelector'))throw Error('autosave removal incomplete');
if(!s.includes('>Сохранить изменения</button>'))throw Error('save button missing');
fs.writeFileSync(p,s);
console.log('Manual save button installed');
