import fs from 'node:fs';
const p='worker-direct.js'; let s=fs.readFileSync(p,'utf8');
if(s.includes('MALINA_ADMIN_NAV_V4')) process.exit(0);
// Dark grouped sidebar.
s=s.replace('.nav{position:fixed;left:0;top:58px;bottom:0;width:210px;background:#fff;border-right:1px solid #e4e6eb;padding:14px;display:flex;flex-direction:column;gap:7px;overflow:auto}.nav a{background:#f4f5f7;border-radius:8px;padding:11px 12px;white-space:nowrap}.nav a:hover{background:#eceef2}',`.nav{position:fixed;left:0;top:58px;bottom:0;width:210px;background:#171922;color:#fff;border-right:1px solid #2b2e3a;padding:14px;display:flex;flex-direction:column;gap:6px;overflow:auto}.nav a{background:#232631;border-radius:8px;padding:10px 12px;white-space:nowrap}.nav a:hover{background:#343846}.nav-title{margin:15px 8px 5px;color:#9ba1b3;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px}.nav-title:first-child{margin-top:2px}`);
const oldNav=s.match(/function nav\(u\)\{return .*?\}\nasync function page/s)?.[0];
if(!oldNav) throw new Error('nav not found');
const newNav=`function nav(u){if(!isAdmin(u))return '<div class="nav"><a href="/?view=overview">Обзор</a><a href="/?view=orders">Заказы</a><a href="/?view=prep">Приготовление</a></div>';return '<div class="nav"><div class="nav-title">Бар</div><a href="/?view=overview">Обзор</a><a href="/?view=orders">Заказы</a><a href="/?view=prep">Приготовление</a><a href="/?view=stock">Склад</a><a href="/?view=inventory">Инвентаризация</a><a href="/?view=menu">Меню</a><a href="/?view=recipes">Техкарты</a><div class="nav-title">Зал</div><a href="/?view=shiftcalc">Текущая смена</a><a href="/?view=shiftlist">Список смен</a><div class="nav-title">Статистика</div><a href="/?view=stats">Бар</a><a href="/?view=shiftstats">Расчёт смен</a></div>'}\nasync function page`;
s=s.replace(oldNav,newNav);
// Remove archive/month statistics from current shift page: current shift is only open/input/close.
const marker="if(isOwner){let months={};";
let a=s.indexOf(marker);
if(a>=0){let end=s.indexOf("}}\n\n if(view==='menu'",a);if(end>0)s=s.slice(0,a)+"}\n\n "+s.slice(end+3);}
// Dedicated shift list and statistics. Periods: whole month, 1-15, 16-end.
const insert=`\n if(view==='shiftlist'&&isAdmin(u)){let cs=s.calcShifts||[],n=v=>Number(v||0),grp=g=>(n(g.ie)-n(g.is))-(n(g.oe)-n(g.os)),tab=t=>n(t.end)-n(t.start),bt=x=>(x.groups||[]).reduce((a,g)=>a+grp(g),0),tt=x=>(x.tables||[]).reduce((a,t)=>a+tab(t),0),ex=x=>(x.expenses||[]).reduce((a,e)=>a+n(e.amount),0),fmt=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n(v));body+='<div class="card"><h2>Список смен</h2><div class="muted">Все расчётные смены привязаны к дате открытия.</div></div><div class="card">'+(cs.slice().reverse().map(x=>'<a class="row" href="/?view=shiftcalc&id='+E(x.id)+'"><div class="grow"><b>'+E(x.businessDate||String(x.opened||'').slice(0,10))+'</b><div class="muted">Открыта '+E(String(x.opened||'').replace('T',' ').slice(0,16))+(x.closed?' · закрыта '+E(String(x.closed).replace('T',' ').slice(0,16)):' · открыта сейчас')+'</div></div><span>Выручка '+fmt(bt(x)+tt(x))+'</span><b>Итог '+fmt(bt(x)+tt(x)-ex(x))+'</b></a>').join('')||'<div class="muted">Смен пока нет</div>')+'</div>'}\n if(view==='shiftstats'&&isAdmin(u)){let cs=s.calcShifts||[],n=v=>Number(v||0),grp=g=>(n(g.ie)-n(g.is))-(n(g.oe)-n(g.os)),tab=t=>n(t.end)-n(t.start),bt=x=>(x.groups||[]).reduce((a,g)=>a+grp(g),0),tt=x=>(x.tables||[]).reduce((a,t)=>a+tab(t),0),ex=x=>(x.expenses||[]).reduce((a,e)=>a+n(e.amount),0),fmt=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n(v)),now=new Date(),month=url.searchParams.get('month')||now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0'),part=url.searchParams.get('part')||'all',rows=cs.filter(x=>{let d=x.businessDate||String(x.opened||'').slice(0,10);if(!d.startsWith(month))return false;let day=Number(d.slice(8,10));return part==='first'?day<=15:part==='second'?day>=16:true}),buttons=rows.reduce((a,x)=>a+bt(x),0),tables=rows.reduce((a,x)=>a+tt(x),0),expenses=rows.reduce((a,x)=>a+ex(x),0);body+='<div class="card"><h2>Статистика · расчёт смен</h2><form class="inline" method="get"><input type="hidden" name="view" value="shiftstats"><input type="month" name="month" value="'+E(month)+'"><select name="part"><option value="all" '+(part==='all'?'selected':'')+'>Весь месяц</option><option value="first" '+(part==='first'?'selected':'')+'>1–15</option><option value="second" '+(part==='second'?'selected':'')+'>16–31</option></select><button class="btn primary">Показать</button></form></div><div class="grid"><div class="card"><div class="muted">Смен</div><div class="big">'+rows.length+'</div></div><div class="card"><div class="muted">Общая выручка</div><div class="big">'+fmt(buttons+tables)+'</div></div><div class="card"><div class="muted">Итог после расходов</div><div class="big">'+fmt(buttons+tables-expenses)+'</div></div></div><div class="card"><div class="row"><span class="grow">Кнопки</span><b>'+fmt(buttons)+'</b></div><div class="row"><span class="grow">Столы</span><b>'+fmt(tables)+'</b></div><div class="row"><span class="grow">Расходы</span><b>'+fmt(expenses)+'</b></div></div>'}\n`;
const pos=s.indexOf(" if(view==='menu'&&isAdmin(u))");if(pos<0)throw new Error('menu insertion point not found');s=s.slice(0,pos)+insert+s.slice(pos);
s=s.replace('/* MALINA_SHIFT_SECTION_V2 MALINA_SHIFT_SECTION_V3 */','/* MALINA_SHIFT_SECTION_V2 MALINA_SHIFT_SECTION_V3 MALINA_ADMIN_NAV_V4 */');
fs.writeFileSync(p,s);console.log('Admin navigation V4 applied');
